sushi_app/urls.py
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.urls import path

from . import views
from .forms import LoginForm
from .reset_views import PasswordResetView,PasswordResetCompleteView,PasswordResetDoneView,PasswordResetConfirmView

urlpatterns = [
    path('delete-directory', views.delete_directory),
    path('delete-directory-file', views.delete_directory_file),
    path('show-directories', views.show_directories),
    path('add-directory-file', views.add_directory_file),
    path('add-directory', views.add_directory),
    path(
        '', views.base, name='base'),
    path(
        'accounts/login/',
        auth_views.LoginView.as_view(
            template_name='authentication_login.html',
            authentication_form=LoginForm), name='login'),
    path(
        'accounts/reset/',
        PasswordResetView.as_view(), name='password_reset'),
    path('accounts/password_reset/done/',
         PasswordResetDoneView.as_view(),
         name='password_reset_done'),

    path('accounts/reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('accounts/reset/done/',
         PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
    path(
        'logout',
        auth_views.LogoutView.as_view(next_page="login"),
        name='logout'),
    path(
        'search', views.search, name='search'),
    path('employee/<int:user_id>', views.employee_info, name='employee_info'),
    path('employee/<int:user_id>/shops_by_sign/<int:sign_id>', login_required(views.EmployeeSignShopsView.as_view()),
         name='employee_sign_shops'),
    path('employee/all', views.employee_list, name='employee_list'),
    path('faq-all', views.faq_list, name='faq_list'),
    path('faq/<int:faq_id>', views.faq_answer, name='faq_answer'),
    path('manager-lk', views.manager_lk_view, name='manager_lk'),
    path('partner-lk', views.partner_lk_view, name='partner_lk'),
    path('partner/new', views.create_partner_view, name='create_partner'),
    path('partner/<int:user_id>', login_required(views.PartnerDetailView.as_view()), name='partner_info'),
    path('partner/edit/<int:user_id>', views.edit_partner_view, name='edit_partner'),
    path('partner/delete/<int:user_id>', login_required(views.PartnerDeleteView.as_view()), name='delete_partner'),
    path('employee/new', views.create_employee_view, name='create_employee'),
    path('employee/edit/<int:user_id>', views.edit_employee_view, name='edit_employee'),
    path('employee/<int:user_id>/tasks/', views.EmployeeTasksListView.as_view(), name='employee_tasks_list'),
    path(
        'request/new', views.form_request_view, name='form_request'),
    path(
        'review/<int:partner_id>/new', views.feedback_form_view, name='form_review'),
    path('notification', views.notification_view, name='notification'),
    path('shop/new', views.shop_form_view, name='shop_form'),
    path(
        'shop/<int:shop_id>',
        login_required(views.ShopListView.as_view()),
        name='shop'),
    path('shop/<int:shop_id>/edit', login_required(views.ShopFormView.as_view()), name='shop_edit'),
    path('shop/<int:shop_id>/delete', login_required(views.ShopDeleteView.as_view()), name='shop_delete'),
    path('shop_sign_detail/<int:pk>', login_required(views.ShopSignDetailView.as_view()), name='shop_sign_detail'),
    path('shop_sign_edit/<int:pk>', login_required(views.ShopSignEditView.as_view()), name='shop_sign_edit'),
    path(
        'task/new/<int:partner_id>', views.form_task_view, name='form_task'),
    path(
        'task/<int:task_id>-<int:user_id>', views.task_view, name='task'),
    path(
        'request/<int:requests_id>-<int:user_id>', views.requests_view, name='request'),
    path(
        'review/<int:feedback_id>-<int:user_id>', views.feedback_view, name='feedback'),
    path('load/request', views.load_filtered_request, name='load_filtered_request'),
    path('load/feedback-shop/<int:shop_id>', views.load_filtered_shop_feedback, name='load_filtered_shop_feedback'),
    path('load/feedback', views.load_filtered_feedback, name='load_filtered_feedback'),
    path('load/tasks', views.load_filtered_tasks, name='load_filtered_tasks'),
    path('load/idea', views.load_filtered_idea, name='load_filtered_ideas'),
    path('load_paginations_docs', views.load_paginations_docs, name='load_paginations_docs'),
    path('load_docs', views.load_docs, name='load_docs'),
    path('load_docs_info/', views.load_docs_info, name='load_docs_info'),
    path('load_notifications/', views.load_notifcations, name='load_notifcations'),
    path('load_pdf_stream_preview/<int:doc_id>', views.load_pdf_stream_preview, name='load_pdf_stream_preview'),
    path('load_excel/<int:doc_id>', views.load_excel, name='load_excel'),
    path('preview-deprecated/<doc_type>/<int:doc_id>', views.preview_deprecated, name='preview_deprecated'),
    path('preview/<doc_type>/<int:doc_id>', views.preview, name='preview'),
    path('notification-settings/', views.notification_settings_view, name='notification_settings'),
    path('notification-rules', views.update_notification_rules, name='notification_rules'),
    path('notification-events', views.notifcation_events, name='notification_events'),
]

sushi_app/models.py
import os

import wagtail.users.models
import wagtail.users.models
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models
from mptt.models import MPTTModel, TreeForeignKey
from phonenumber_field.modelfields import PhoneNumberField
from wagtail.core.fields import RichTextField
from wagtail.documents.models import Document, AbstractDocument

from mickroservices.models import DocumentSushi
from sushi_app.utils import create_dict_from_choices
from .enums import *
from .enums import *


class Directory(MPTTModel):
    title = models.CharField("Название", max_length=100)
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')

    class Meta:
        verbose_name = "Папка"
        verbose_name_plural = "Папки"

    def __str__(self):
        return self.title


def get_upload_path(instance, filename):
    return os.path.join('directory_files', instance.directory.title, filename)


class DirectoryFile(models.Model):
    directory = models.ForeignKey(Directory, related_name='directory_files', on_delete=models.CASCADE)
    dir_file = models.FileField("Файл", upload_to=get_upload_path)

    def filename(self):
        return os.path.basename(self.dir_file.name)


class Department(models.Model):
    name = models.CharField(max_length=256, db_index=True)

    def __str__(self):
        return f"{self.name}"


class UserProfile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='user_profile'
    )
    wagtail_profile = models.OneToOneField(
        wagtail.users.models.UserProfile, on_delete=models.CASCADE, related_name='user_profile',
        null=True, blank=True
    )
    position = models.CharField(max_length=100, blank=True)
    phone_number = PhoneNumberField(null=True, blank=True)
    whatsapp = PhoneNumberField(null=True, blank=True)
    twitter = models.URLField(null=True, max_length=200, blank=True)
    facebook = models.URLField(null=True, max_length=200, blank=True)
    instagram = models.URLField(null=True, max_length=200, blank=True)
    key_responsibilities = RichTextField(blank=True)
    is_partner = models.BooleanField(default=False)
    is_manager = models.BooleanField(default=False)
    is_head = models.BooleanField(blank=True, default=False)
    manager = models.ForeignKey(on_delete=models.SET_NULL, to='self', related_name='partner',
                                null=True, blank=True, limit_choices_to={'is_manager': True})
    head = models.ForeignKey(on_delete=models.SET_NULL, to='self', related_name='employee',
                             null=True, blank=True, limit_choices_to={'is_head': True})
    department = models.ForeignKey(on_delete=models.SET_NULL, to=Department, related_name='member',
                                   null=True, blank=True)
    scan = models.FileField(upload_to='images', blank=True)
    middle_name = models.CharField(max_length=100, null=True, blank=True)
    ddk_number = models.CharField(max_length=200, null=True, blank=True)
    comment = models.TextField(null=True, blank=True, verbose_name="Комментарий к пользователю")

    def __str__(self):
        return self.user.get_full_name()

    @property
    def user_is_manager(self):
        return self.is_manager or self.is_head

    def save(self, *args, **kwargs):
        models = []
        ll = {
            'request',
            'messege',
            'question',
            'news',
            'feedback',
            'shop',
            'idea',
            'materials',
        }
        for ls in ll:
            sub = Subscribes(user_id=self.user,
                             event_type=ls,
                             subscribe_type='site')
            models.append(sub)
            sub = Subscribes(user_id=self.user,
                             event_type=ls,
                             subscribe_type='email')
            models.append(sub)
        Subscribes.objects.bulk_create(models)
        super().save(*args, **kwargs)


class Task(models.Model):
    responsible = models.ForeignKey(on_delete=models.CASCADE, to=settings.AUTH_USER_MODEL,
                                    related_name='task_responsible')
    manager = models.ForeignKey(on_delete=models.CASCADE, to=UserProfile, related_name='task_manager',
                                limit_choices_to={'is_manager': True})
    title = models.CharField(max_length=256)
    description = models.TextField()
    date_create = models.DateTimeField(auto_now_add=True)
    status = models.SmallIntegerField(choices=STATUS_CHOICE, default=ST_IN_PROGRESS)

    def __str__(self):
        return '{0} | {1} | {2}'.format(
            self.id,
            self.date_create,
            create_dict_from_choices(STATUS_CHOICE)[self.status]
        )


class Requests(models.Model):
    responsible = models.ForeignKey(on_delete=models.CASCADE, to=settings.AUTH_USER_MODEL,
                                    related_name='requests_responsible')
    manager = models.ForeignKey(on_delete=models.CASCADE, to=UserProfile, related_name='requests_manager',
                                limit_choices_to={'is_manager': True})
    title = models.CharField(max_length=256)
    description = models.TextField()
    date_create = models.DateTimeField(auto_now_add=True)
    status = models.SmallIntegerField(choices=STATUS_CHOICE, default=ST_IN_START)

    def __str__(self):
        return '{0} | {1} | {2}'.format(
            self.id,
            self.date_create,
            create_dict_from_choices(STATUS_CHOICE)[self.status]
        )


class RequestFile(models.Model):
    request = models.ForeignKey(Requests, on_delete=models.CASCADE, related_name='files')
    file = models.FileField(upload_to='requests', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)


class ShopSign(models.Model):
    title = models.CharField(max_length=255, verbose_name='Наименование')
    icon = models.ImageField('Иконка', blank=True, null=True)

    def __str__(self):
        return f"{self.title}"

    class Meta:
        verbose_name = 'Признак магазин'
        verbose_name_plural = 'Признаки магазинов'


class Shop(models.Model):
    address = models.CharField(max_length=255, blank=False, null=False,
                               verbose_name='Адрес магазина')
    city = models.CharField(max_length=255)
    entity_name = models.CharField(max_length=255)
    docs = models.ManyToManyField(
        DocumentSushi,
        blank=True,
        related_name='+'
    )
    checks = models.ManyToManyField(
        DocumentSushi,
        blank=True,
        related_name='+'
    )
    partner = models.ForeignKey(on_delete=models.DO_NOTHING, to=UserProfile,
                                limit_choices_to={'is_partner': True}, related_name='shop_partner')
    responsibles = models.ManyToManyField(to=UserProfile,
                                          limit_choices_to={'is_manager': True}, related_name='shop_responsible')
    date_create = models.DateTimeField(auto_now_add=True)
    file = models.FileField(blank=True)
    details = models.TextField(blank=True)
    signs = models.ManyToManyField(ShopSign, blank=True,
                                   related_name='shop_sings')

    def __str__(self):
        return f"{self.city} {self.address}"

    class Meta:
        verbose_name = 'Магазин'
        verbose_name_plural = 'Магазины'


class Product(models.Model):
    user = models.ForeignKey(on_delete=models.CASCADE, to=settings.AUTH_USER_MODEL, related_name='user')
    title = models.CharField(max_length=256)
    short_descrip = models.CharField(max_length=256)
    descrip = models.TextField()
    composition = models.TextField()
    characteristics = models.TextField()
    date_update = models.DateTimeField(auto_now=True, blank=True, null=True)
    date_create = models.DateTimeField(auto_now_add=True)
    RATING_CHOICE = (
        (1, "Ужасно"),
        (2, "Плохо"),
        (3, "Нормально"),
        (4, "Хорошо"),
        (5, "Отлично"),
    )
    rating = models.IntegerField(choices=RATING_CHOICE, default=5)
    files = models.ImageField(blank=True)

    def __str__(self):
        return f" {self.title}, дата: {self.date_create}"

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'


class Feedback(models.Model):
    ST_SOLVED, ST_NOT_SOLVED = range(2)
    STATUS_CHOICE = (
        (ST_SOLVED, "Отработан"),
        (ST_NOT_SOLVED, "Не отработан"),
    )
    responsible = models.ForeignKey(on_delete=models.CASCADE, to=UserProfile,
                                    related_name='feed_responsible')
    manager = models.ForeignKey(on_delete=models.CASCADE, to=UserProfile, related_name='feed_manager',
                                limit_choices_to={'is_manager': True})
    shop = models.ForeignKey(on_delete=models.CASCADE, to=Shop)
    date_create = models.DateTimeField(auto_now_add=True)
    date_pub = models.DateField()
    status = models.SmallIntegerField(choices=STATUS_CHOICE, default=ST_NOT_SOLVED)
    description = models.TextField()
    source = models.CharField(max_length=256)

    def __str__(self):
        return '{0} | {1} | {2}'.format(
            self.id,
            self.date_create,
            create_dict_from_choices(STATUS_CHOICE)[self.status]
        )


class Messeges(models.Model):
    from_user = models.ForeignKey(on_delete=models.CASCADE, to=settings.AUTH_USER_MODEL, related_name='user_messeges')
    to_user = models.ForeignKey(on_delete=models.CASCADE, to=settings.AUTH_USER_MODEL, related_name='to_user')
    task = models.ForeignKey(on_delete=models.CASCADE, to=Task, blank=True, null=True)
    requests = models.ForeignKey(on_delete=models.CASCADE, to=Requests, blank=True, null=True)
    feedback = models.ForeignKey(on_delete=models.CASCADE, to=Feedback, blank=True, null=True)
    text = models.TextField(null=True, blank=True)

sushi_app/templates/partials/documents.html
{% load static %}
{% load wagtailcore_tags %}

<!-- этот элемент нужен для индикации перезагрузки информационного блока -->
<div id="refresh-container" refresh-token="{{ refresh_token }}"></div>

{% for document in documents %}
    <div class="col-md-6 col-lg-4 p-1">
        <div class="project-attachment ui-bordered p-2">

            <div class="project-attachment-img" style="background-image: url({{ document.preview }})"
                 doc-id="{{ document.id }}"></div>
            <div class="media-body ml-3">
                <strong class="project-attachment-filename">{{ document.title }}</strong>
                <div class="text-muted small">{{ document.file_size|filesizeformat }}</div>
                <div>
                    <a href="{{ document.url }}" download="">Загрузить</a>
                </div>
            </div>
            {% if user.user_profile.user_is_manager %}

                <div class="btn-group project-actions align-self-start">
                    <button type="button"
                            class="btn btn-sm btn-default icon-btn borderless btn-round md-btn-flat dropdown-toggle hide-arrow"
                            data-toggle="dropdown">
                        <i class="ion ion-ios-more"></i>
                    </button>
                    <div class="dropdown-menu dropdown-menu-right">
                        <a class="dropdown-item" href="/cms/documents/edit/{{ document.id }}/" target="_blank">Редактировать</a>
                        <a class="dropdown-item" href="/cms/documents/delete/{{ document.id }}/"
                           target="_blank">Удалить</a>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
{% endfor %}

sushi_app/templates/partials/feedback_manager.html
{% for review in feedback_list %}
    <div class="col-md-6 mb-4">
        <div class="card hoverable h-100">
            <div class="card-header d-flex justify-content-between  align-items-start">
                <div>
                    <div>
                        <a href="{% url 'employee_info' review.responsible.user.id %}"
                           class="font-weight-semibold">{{ review.responsible.user.get_full_name }}</a>

                        {% if review.responsible.phone_number %}
                            <span class="text-muted">{{ review.responsible.phone_number }}</span>
                        {% endif %}

                        {% if review.status == 0 %}
                            <span class="badge badge-outline-success badge-pill">отработан</span>
                        {% elif review.status == 1 %}
                            <span class="badge badge-outline-danger badge-pill">не отработан</span>
                        {% endif %}
                    </div>
                    <div class="small">
                        <span class="text-muted">{{ review.date_create|date:'d.m.Y' }}</span>
                        <br>
                        <span class="text-muted">Магазин: {{ review.shop.address }}</span>
                    </div>
                    <div class="small">
                        <a href="{% url 'feedback' review.id user.id %}" class="text-primary">Подробнее</a>
                    </div>
                </div>

                                                        <div class="btn-group project-actions">
                                                            <button type="button" class="btn btn-sm btn-default icon-btn borderless btn-round md-btn-flat dropdown-toggle hide-arrow" data-toggle="dropdown">
                                                                <i class="ion ion-ios-more"></i>
                                                            </button>
                                                            <div class="dropdown-menu dropdown-menu-right">
                                                                <a class="dropdown-item" href="{% url 'feedback' review.id user.id %}">Просмотр</a>
{#                                                                <a class="dropdown-item" href="javascript:void(0)">Удаление</a>#}
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="card-body">
                                                        <div>{{ review.description|truncatewords:8 }}</div>
                                                    </div>
                                                </div>
                                            </div>
                                            {% endfor %}

sushi_app/templates/partials/ideas_manager.html
{% csrf_token %}
{{ formset.management_form }}
												{% for forms in formset %}
                                                    {% for idea in idea_list %}
                                                        {% if forloop.counter == forloop.parentloop.counter %}
                                        {{ forms.id }}
                                            <div class="col-md-6 mb-4">
                                                <div class="card hoverable h-100">
                                                    <div class="card-header d-flex justify-content-between  align-items-start">
                                                        <div>
                                                            <div class="small">
                                                                <a href="{% url 'employee_info' idea.sender.id %}" class="text-dark">{{ idea.sender.get_full_name }}</a>
                                                                <span class="text-muted">{{ idea.date_created }}</span>
                                                            </div>
                                                            <div class="btn-group">
                                                                {{ forms.status }}
                                                                <button class="btn btn-warning btn-xs btn-round" type="submit">Сохранить</button>
                                                            </div>
{#                                                            <div class="small mt-2">#}
{#                                                                <a href="#" class="text-primary">Подробнее</a>#}
{#                                                            </div>#}
                                                        </div>


                                                    </div>
                                                    <div class="card-body">
                                                        <div>Описание идеи: {{ idea.body }}</div>
                                                        {% for file in idea.files.all %}<div>Файл: <a href="{{ file.file.url }}" class="text-primary" download="">{{ file.file }}</a></div>
                                                            {% empty %}{% endfor %}
                                                    </div>
                                                </div>
                                            </div>
                                                        {% endif %}
                                            	{% endfor %}{% endfor %}

sushi_app/templates/partials/request_manager.html
{% load class_tag %}
{% for task in request_list %}
    <div class="col-md-6 mb-4">
        <div class="card hoverable h-100">
            <div class="card-header d-flex justify-content-between  align-items-start">
                <div>
                    <div>
                        <span class="font-weight-semibold">{{ task.title }}</span>
                        {% if task.status == 0 %}
                            <span class="badge badge-outline-success badge-pill">решен</span>
                        {% elif task.status == 1 %}
                            <span class="badge badge-outline-warning badge-pill">обрабатывается</span>
                        {% elif task.status == 2 %}
                            <span class="badge badge-outline-danger badge-pill">не решена</span>
                        {% elif task.status == 3 %}
                            <span class="badge badge-primary badge-pill">создана</span>
                        {% endif %}
                    </div>
                    <div class="small">
                        <a href="{% url 'employee_info' task.responsible.id %}"
                           class="text-dark">{{ task.responsible.get_full_name }}</a>
                        <span class="text-muted">{{ task.date_create.date }}</span>
                    </div>
                    <div class="small">
                        {% if task|get_class == 'Requests' %}
                            <a href="{% url 'request' task.id user.id %}" class="text-primary">Подробнее</a>
                        {% else %}
                            <a href="{% url 'task' task.id user.id %}" class="text-primary">Подробнее</a>
                        {% endif %}
                    </div>
                </div>
                <div class="btn-group project-actions">
                    <button type="button"
                            class="btn btn-sm btn-default icon-btn borderless btn-round md-btn-flat dropdown-toggle hide-arrow"
                            data-toggle="dropdown">
                        <i class="ion ion-ios-more"></i>
                    </button>
                    <div class="dropdown-menu dropdown-menu-right">
                        {% if task|get_class == 'Requests' %}
                            <a class="dropdown-item" href="{% url 'request' task.id user.id %}">Просмотр</a>
                        {% else %}
                            <a class="dropdown-item" href="{% url 'task' task.id user.id %}">Просмотр</a>
                        {% endif %}
                        {#<a class="dropdown-item" href="javascript:void(0)">Удаление</a>#}
                    </div>
                </div>
            </div>
            <div class="card-body">
                <div>{{ task.description|truncatewords:8 }}</div>
            </div>
        </div>
    </div>
{% endfor %}

sushi_app/templates/partials/tasks_manager.html
{% for task in task_list %}
    <div class="col-md-6 mb-4">
        <div class="card hoverable h-100">
            <div class="card-header d-flex justify-content-between  align-items-start">
                <div>
                    <div>
                        <span class="font-weight-semibold">{{ task.title }}</span>
                        {% if task.status == 0 %}
                        <span class="badge badge-outline-success badge-pill">решен</span>
                        {% elif task.status == 1 %}
                        <span class="badge badge-outline-warning badge-pill">обрабатывается</span>
                        {% elif task.status == 2 %}
                        <span class="badge badge-outline-danger badge-pill">не решена</span>
                        {% endif %}
                    </div>
                    <div class="small">
                        <a href="{% url 'employee_info' task.responsible.id %}" class="text-dark">{{ task.responsible.get_full_name }}</a>
                        <span class="text-muted">{{ task.date_create.date }}</span>
                    </div>
                <div class="small">
                    <a href="{% url 'task' task.id user.id %}" class="text-primary">Подробнее</a>
                </div>
                </div>
                <div class="btn-group project-actions">
                    <button type="button" class="btn btn-sm btn-default icon-btn borderless btn-round md-btn-flat dropdown-toggle hide-arrow" data-toggle="dropdown">
                        <i class="ion ion-ios-more"></i>
                    </button>
                    <div class="dropdown-menu dropdown-menu-right">
                        <a class="dropdown-item" href="{% url 'task' task.id user.id %}">Просмотр</a>
                        {#<a class="dropdown-item" href="javascript:void(0)">Удаление</a>#}
                    </div>
                </div>
            </div>
            <div class="card-body">
                <div>{{ task.description|truncatewords:8 }}</div>
            </div>
        </div>
    </div>
{% endfor %}