mickroservices/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from mickroservices import views

app_name = 'mickroservices'

urlpatterns = [
    path('faq/',
         login_required(views.QuestionView.as_view()),
         name='faq'),

    path('ideas/',
         login_required(views.IdeaView.as_view()),
         name='idea'),

    path('lessons/',
         login_required(views.CoursesView.as_view()),
         name='lessons'),
    path('lesson/<int:pk>',
         login_required(views.CourseView.as_view()),
         name='lesson'),

    path('news/',
         login_required(views.NewsView.as_view()),
         name='news'),
    path('news/new/',
         login_required(views.NewsCreateView.as_view()),
         name='news_new'),
    path('news/edit/<int:pk>',
         login_required(views.NewsEditView.as_view()),
         name='news_edit'),
    path(
        'news/delete/<int:pk>',
        login_required(views.NewsDeleteView.as_view()),
        name='news_delete'
    ),
    path('marketing/',
         login_required(views.MarketingView.as_view()),
         name='marketing'),

    path('schedule/<int:pk>',
         login_required(views.ScheduleView.as_view()),
         name='schedule_view'),
    path('schedule/new/',
         login_required(views.ScheduleCreateView.as_view()),
         name='schedule_new'),
    path('schedule/',
         login_required(views.ScheduleListView.as_view()),
         name='schedule'),
    path('tech_cards/',
         login_required(views.TechCardsListView.as_view()),
         name='tech_cards'),
    path('regulations/',
         login_required(views.RegulationsListView.as_view()),
         name='regulations'),    
]

mickroservices/models.py
from django.db import models



class QuestionModel(models.Model):
    """docstring for FAQModel"""

    ST_CONSIDERATION, ST_OK, ST_REJECTED = range(3)
    STATUS_CHOICE = (
        (ST_CONSIDERATION, "На рассмотрении"),
        (ST_OK, "Одобрено"),
        (ST_REJECTED, "Отклонено"),
    )

    name = models.CharField(max_length=255, blank=False, null=False,
                            verbose_name='Имя отправителя')
    phone_number = models.CharField(max_length=12, null=False,blank=False,
                                    verbose_name='Номер телефона')
    email = models.EmailField(blank=False, null=False, verbose_name='Email')
    theme = models.CharField(max_length=100, blank=False, null=False,
                             verbose_name='Тема')
    body = models.CharField(max_length=1000, blank=False, null=False,
                            verbose_name='Сообщение')
    status = models.IntegerField(choices=STATUS_CHOICE, default=ST_CONSIDERATION)

    class Meta:
        verbose_name = 'Вопрос от пользователя'
        verbose_name_plural = 'Вопросы от пользоватлей'

mickroservices/models/idea.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from django.conf import settings

class IdeaModel(models.Model):
    """docstring for IdeaModel"""

    ST_CONSIDERATION, ST_OK, ST_REJECTED = range(3)
    STATUS_CHOICE = (
        (ST_CONSIDERATION, "На рассмотрении"),
        (ST_OK, "Одобрено"),
        (ST_REJECTED, "Отклонено"),
    )
    sender = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='sender_idea', blank=True, null=True)
    recipient = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='recipient_idea', blank=True, null=True)
    email = models.EmailField(blank=True, null=True, verbose_name='Email')
    phone_number = PhoneNumberField(null=True, blank=True,
                                    verbose_name='Номер телефона')    
    body = models.CharField(max_length=1000, blank=False, null=False,
                            verbose_name='Сообщение')
    status = models.IntegerField(choices=STATUS_CHOICE, default=ST_CONSIDERATION)
    answer = models.CharField(max_length=1000, blank=False, null=False,
                              verbose_name='Ответ')
    date_created = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    date_answer = models.DateTimeField(auto_now_add=True, verbose_name='Дата оповещения автора')

    class Meta:
        verbose_name = 'Идея от пользователя'
        verbose_name_plural = 'Идеи от пользоватлей'
        ordering = ['-date_created']

    def __str__(self):
        return f'{self.body} от {self.email}'


class IdeaFile(models.Model):
    idea = models.ForeignKey(IdeaModel, on_delete=models.CASCADE, related_name='files')
    file = models.FileField(upload_to='ideas', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

mickroservices/models/news.py
from django.db import models
from django.urls import reverse
from django.db.models import Q

from wagtail.core.models import Page
from wagtail.core.fields import RichTextField
from wagtail.admin.edit_handlers import FieldPanel
from wagtail.images.edit_handlers import ImageChooserPanel


class NewsPage(Page):
    image = models.ForeignKey(
        'wagtailimages.Image',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='+'
    )
    preview = RichTextField(blank=True)
    body = RichTextField(blank=True)
    announcement = models.TextField(blank=True)

    content_panels = Page.content_panels + [
        FieldPanel('body', classname="full"),
        ImageChooserPanel('image'),
    ]

    class Meta:
        verbose_name = "Новости"

    @classmethod
    def get_live(cls):
        # получения в статусе опубликованна
        is_live = cls.objects.filter(live=True)
        # wagtail публикация
        wagtail_pub = is_live.filter(Q(go_live_at=None) | Q(go_live_at__lt=timezone.now()))
        # Реализация в проекте
        return wagtail_pub.filter(Q(first_published_at=None) | Q(first_published_at__lt=timezone.now()))

    def get_context(self, request):
        context = super(NewsPage, self).get_context(request)
        context['breadcrumb'] = [
            {'title': 'Новости',
             'url': reverse('mickroservices:news')},
            {'title': self.title}
        ]
        return context

mickroservices/forms/idea.py
from django import forms

from mickroservices.models import IdeaModel


class IdeaForm(forms.ModelForm):
    # email = forms.CharField(validators=[EmailValidator])
    class Meta:
        model = IdeaModel
        exclude = ['status', 'answer', 'date_answer', 'date_created', 'file',]
        widgets = {
            'body': forms.Textarea(attrs={'rows': 2}),
        }


class IdeaStatusForm(forms.ModelForm):
    class Meta:
        model = IdeaModel
        fields = ['status']
        widgets = {
            'status': forms.Select(attrs={'class': 'btn btn-warning btn-xs btn-round dropdown-toggle'})
        }

mickroservices/views/idea.py
from django.conf import settings
from django.template.response import TemplateResponse
from django.views.generic.edit import FormView
from django.urls import reverse_lazy

from mickroservices.models import IdeaModel
from mickroservices.forms import IdeaForm
from mickroservices.models.idea import IdeaFile
from mickroservices.utils import send_message
from chat.models import Message as Chat_Message


class IdeaView(FormView):
    """ """
    template_name = 'idea.html'
    success_url = reverse_lazy('idea')
    form_class = IdeaForm

    def get_context_data(self, **kwargs):
        ctx = super(IdeaView, self).get_context_data(**kwargs)
        # ctx['ideas_ok'] = IdeaModel.objects.filter(status=IdeaModel.ST_OK)[:5]
        ctx['breadcrumb'] = [{'title': 'Идеи'}]
        return ctx

    def post(self, request, *args, **kwargs):
        form = IdeaForm(request.POST or None, request.FILES or None)
        ctx = self.get_context_data(**kwargs)
        if form.is_valid():
            idea = form.save(commit=False)
            idea.sender = self.request.user
            idea.recipient = self.request.user.user_profile.manager.user
            idea.save()
            if 'file' in request.FILES:
                for f in request.FILES.getlist('file'):
                    IdeaFile.objects.create(file=f, idea=idea)
            Chat_Message.objects.create(
                sender=self.request.user,
                recipient=self.request.user.user_profile.manager.user,
                body="Была предложена идея",
                idea=idea
            )
            ctx.update(self.form_valid_send_message(
                form,
                'Ваша идея принята на рассмотрение!',
                settings.DEFAULT_SUPORT_EMAIL,
                self.get_context_data(**kwargs)))
            ctx['status'] = 'Ваша идея принята на рассмотрение!'
        else:
            ctx['errors'] = f'Ошибка заполнения полей: {form.errors}'

        return TemplateResponse(request, self.template_name, ctx)

    def form_valid_send_message(self, form, subject, to_email, ctx):
        if form.is_valid():
            error = send_message(template='emails/email_idea.html',
                                 subject=subject,
                                 ctx={},
                                 to_email=to_email,
                                 request=self.request)
            if not error:

                ctx['status'] = 'email_send'
            else:
                ctx['errors'] = 'Ошибка отправления письма'
        else:
            ctx[
                'errors'] = 'Что-то пошло не так: одно из полей было заполнено некорректно. Повторите попытку отправки формы.'
        return ctx

mickroservices/views/marketing_material.py
from django.http import HttpResponseBadRequest, JsonResponse
from django.views.generic import ListView
from django.views.decorators.vary import vary_on_headers
from django.utils.encoding import force_text
from wagtail.documents.forms import get_document_form
from wagtail.documents.permissions import permission_policy

from mickroservices.models import MarketingMaterial
from mickroservices.models import DocumentSushi, DocumentPreview
from mickroservices.utils import FileConverter

from os import path
from django.conf import settings



def get_marketing_documents(doc_type=4):
    documents = DocumentSushi.objects.filter(doc_type=doc_type)
    return documents

class MarketingView(ListView):
    template_name = 'marketingmaterial.html'
    model = MarketingMaterial
    paginate_by = 9
    context_object_name = 'materials'

    def get_context_data(self, **kwargs):
        context = super(MarketingView, self).get_context_data(**kwargs)

        context['types_marketing'] =MarketingMaterial.TYPE_CHOICE
        context['breadcrumb'] = [{'title': 'Маркетинговые материалы'}]
        #context['documents'] = get_marketing_documents()
        context['active_tab'] = MarketingMaterial.T_PROMOTIONS
        return context

    def verife_http_response(self, request):
        if not request.is_ajax():
            return HttpResponseBadRequest("Cannot POST to this view without AJAX")

        if not request.FILES:
            return HttpResponseBadRequest("Must upload a file")
        return None

    def get_doc_form(self, request):
        # Build a form for validation
        DocumentForm = get_document_form(DocumentSushi)
        return DocumentForm(
            {
                "title": request.FILES["file"].name,
                "collection": request.POST.get("collection"),
            },
            {"file": request.FILES["file"]},
            user=request.user,
        )

    def save_doc(self,request, doc, doc_type):
        doc.doc_type = doc_type
        doc.uploaded_by_user = request.user
        doc.file_size = doc.file.size

        # Set new document file hash
        doc.file.seek(0)
        doc._set_file_hash(doc.file.read())
        doc.file.seek(0)
        doc.save()


    @vary_on_headers("X-Requested-With")
    def post(self, request, *args, **kwargs):

        respone = self.verife_http_response(request)
        if respone:
            return respone

        form = self.get_doc_form(request)

        if form.is_valid():
            # Save it
            doc = form.save(commit=False)

            doc_type = request.POST.get("type")

            self.save_doc(request, doc, doc_type)

            return JsonResponse({"success": True})
        else:
            # Validation error
            return JsonResponse(
                {
                    "success": False,
                    "error_message": "\n".join(
                        [
                            "\n".join([force_text(i) for i in v])
                            for k, v in form.errors.items()
                        ]
                    ),
                }
            )

mickroservices/views/news.py
from django.core.exceptions import PermissionDenied
from django.http import HttpResponseRedirect
from django.template.response import TemplateResponse
from django.urls import reverse_lazy
from django.utils.text import slugify
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from wagtail.core.models import Page

from mickroservices.forms import NewsForm
from mickroservices.models import NewsPage
from django.utils import timezone

class NewsView(ListView):
    template_name = 'news.html'
    model = NewsPage
    paginate_by = 9
    context_object_name = 'news'
    ordering = 'first_published_at'

    def get_queryset(self):
        news_all = self.model.get_live().order_by('first_published_at')
        return news_all

    def get_context_data(self, **kwargs):
        context = super(NewsView, self).get_context_data(**kwargs)
        context['breadcrumb'] = [{'title': 'Новости'}]
        return context


class NewsCreateView(CreateView):
    template_name = 'news_form.html'
    form_class = NewsForm
    success_url = reverse_lazy('mickroservices:news')

    def dispatch(self, request, *args, **kwargs):
        if not (self.request.user.user_profile.is_manager or self.request.user.user_profile.is_head):
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(NewsCreateView, self).get_context_data(**kwargs)
        context['title'] = 'Создание новости'
        context['breadcrumb'] = [
            {'title': 'Новости',
             'url': reverse_lazy('mickroservices:news')},
            {'title': context['title']}
        ]
        return context

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.slug = slugify(self.object.title, allow_unicode=True)
        self.object.seo_title = self.object.title
        homepage = Page.objects.get(url_path='/home/')
        homepage.add_child(instance=self.object)
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, form, ms='Ошибка заполнения формы'):
        print(form.errors)
        print(form.cleaned_data)
        return TemplateResponse(self.request,
                                self.template_name,
                                {'form': form,
                                 'status_ms': True,
                                 'message': ms})


class NewsEditView(UpdateView):
    template_name = 'news_form.html'
    form_class = NewsForm
    model = NewsPage
    success_url = reverse_lazy('mickroservices:news')

    def dispatch(self, request, *args, **kwargs):
        if not self.request.user.user_profile.user_is_manager:
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(NewsEditView, self).get_context_data(**kwargs)
        context['title'] = 'Редактирование новости'
        context['breadcrumb'] = [
            {'title': 'Новости',
             'url': reverse_lazy('mickroservices:news')},
            {'title': context['title']}
        ]
        return context

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.slug = slugify(self.object.title, allow_unicode=True)
        self.object.seo_title = self.object.title
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, form, ms='Ошибка заполнения формы'):
        print(form.errors)
        print(form.cleaned_data)
        return TemplateResponse(self.request,
                                self.template_name,
                                {'form': form,
                                 'status_ms': True,
                                 'message': ms})


class NewsDeleteView(DeleteView):
    model = NewsPage
    template_name = 'delete_news.html'
    success_url = reverse_lazy('mickroservices:news')

    def get_success_url(self):
        return self.success_url

    def dispatch(self, request, *args, **kwargs):
        if not self.request.user.user_profile.user_is_manager:
            raise PermissionDenied
        return super().dispatch(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        if "cancel" in request.POST:
            url = self.get_success_url()
            return HttpResponseRedirect(url)
        else:
            return super(NewsDeleteView, self).post(request, *args, **kwargs)

mickroservices/templates/delete_news.html
{% extends 'layout.html' %}
{% load wagtailcore_tags %}

{% block body_class %}template-blogindexpage{% endblock %}

{% block title %}Удалить новость?{% endblock %}



{% block  breadcrumb %}
    {% include 'partials/breadcrumb.html' %}
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <p>Вы действительно хотите удалить новость "{{ object }}"?</p>
        <input type="submit" value="ДА" class="btn btn-round btn-outline-primary">
        <input type="submit" name="cancel" value="Нет" class="btn btn-round btn-outline-primary"/>
    </form>
{% endblock %}

mickroservices/templates/idea.html
{% extends 'layout.html' %}
{% load widget_tweaks %}
{% load static %}

{% block title %}Идеи{% endblock %}
{% block page_title %}
    <h2 class="text-light font-weight-normal mt-4 mb-1">Идеи</h2>
{% endblock %}

{% block  breadcrumb%}
    {% include 'partials/breadcrumb.html' %}
{% endblock %}

 {% block content %}
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    <div class="card my-4">
        <div class="card-body">
            <form action="{% url 'mickroservices:idea' %}" enctype="multipart/form-data" method="post">
                {% csrf_token %}
                <h4>Предложить идею</h4>
                {% comment %}
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label class="form-label">Email</label>
                        {% render_field form.email placeholder="Email" class+="form-control" %}
                    </div>
                    <div class="form-group col-md-6">
                        <label class="form-label">Телефон</label>
                        {% render_field form.phone_number placeholder="Телефон" class+="form-control" %}
                    </div>
                </div>
                {% endcomment %}
                <div class="form-group">
                    <label class="form-label">Идея</label>
                    {% render_field form.body placeholder="Идея" class+="form-control" %}
                    </div>
                    <div class="form-group">
                    <label class="form-label">Файл</label>
                        <input type="file" name="file" id="id_file" multiple>
                </div>
                <div class="text-right">
                    <button class="btn btn-primary btn-round">Отправить</button>
                </div>
            </form>
            {{status}}
            {{errors}}
        </div>
    </div>
{#    {% if ideas_ok %}#}
{#        <div class="my-4">#}
{#            <h4>Последние идеи</h4>#}
{#            {% for idea in ideas_ok %}#}
{#                <div class="bg-white ui-bordered mb-2">#}
{#                    <a href="#company-faq-1" class="d-flex justify-content-between text-dark py-3 px-4" data-toggle="collapse">#}
{#                        {{idea.email}}#}
{#                        <span class="collapse-icon"></span>#}
{#                    </a>#}
{#                    <div id="company-faq-1" class="collapse text-muted">#}
{#                        <div class="px-4 pb-3">{{idea.body}}</div>#}
{#                    </div>#}
{#                </div>#}
{#            {% endfor %}#}
{#        </div>#}
{#    {% endif %}#}
 {% endblock %}

 {% block extrascripts %}
    <script src="{% static "js/jquery.mask.min.js" %}"></script>
    <script type="text/javascript">
        $(document).ready(function(){
            $("#id_phone_number").mask("0 (000) 000-00-00")
        });
    </script>
 {% endblock %}

mickroservices/templates/lessons.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}Обучение{% endblock %}
{% block page_title %}
    <h2 class="text-light font-weight-normal mt-4 mb-1">Обучение</h2>
{% endblock %}

{% block  breadcrumb %}
    {% include 'partials/breadcrumb.html' %}
{% endblock %}

{% block content %}
    <div class="responsive-video mb-4">
        <iframe src="https://www.youtube.com/embed/Hen8tPH0A2w" frameborder="0"
                allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                allowfullscreen></iframe>
    </div>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore
        magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
        consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla
        pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est
        laborum.</p>
    <div class="preview-content">
        <button id="show-preview-button" class="btn btn-light">Скрыть</button>
    </div>
    <div class="nav">
        {% for item in subjects %}
            <li class="nav-item">
                <a data-id={{ item.pk }} class="nav-mm nav-link {% if subjects.0.pk == item.pk %}text-dark{% endif %}
                   pl-0" href="javascript:void(0)" onclick="load_tech_cards_docs($(this))">{{ item.name }}</a>
            </li>
        {% endfor %}
    </div>
    {% if user.userprofile.user_is_manager %}
        <div class="my-4">
            <form action="{{ request.path }}" class="dropzone needsclick" id="dropzone-files" method='post'>
                {% csrf_token %}

                <div class="dz-message needsclick">
                    Перетащите файлы сюда или нажмите, чтобы загрузить
                </div>
                <div class="fallback">
                    <input name="file" type="file" multiple>
                </div>
                <input type="hidden" name="type" value="{{ doc_type }}">
                <input type="hidden" name="sub_type" value="{{ subjects.all.0.pk }}">
            </form>
        </div>
    {% endif %}
    <div class="my-5">
        <div class="row mt-3">
            <div class="col-12">
                <form class="input-group search-form" action="{{ request.path }}" method="get" novalidate="">
                    <div class="input-group-prepend">
                        <i class="input-group-text ion-ios-search"></i>
                    </div>

                    <input type="search" name="q" class="form-control" placeholder="Поиск...">
                    <input type="submit" value="Search" class="button" style="display:none">
                </form>
            </div>
        </div>
    </div>
    <div class="my-5">
        <div class="my-4 small text-right">
            <span class="text-muted">Сортировать: </span>
            <a href="?ordering=title" class="text-muted active">По порядку</a>
            <a href="?ordering=-created_at" class="text-muted">По дате</a>
            <a href="?ordering=file_size" class="text-muted">По размеру</a>
        </div>
        <div class="row" id="documents_wraper">
            <!-- {% include 'partials/documents.html' with documents=documents %} -->
        </div>
        <div id="pagination">
            <!--
        {% if is_paginated %}
            {% include 'partials/pagination.html' with posts=page_obj %}
        {% endif %}
    -->
        </div>
    </div>
    <div class="my-5">
        <div class="row">
            {% for course in object_list %}
                <div class="col-md-4 mb-5">
                    <div class="card hoverable">
                        <div class="card-body">
                            <h4 class="card-title mb-3">{{ course.title }}</h4>
                            <p class="card-text">{{ course.description|truncatechars:25 }}</p>
                            <a href="{% url 'mickroservices:lesson' course.id %}"
                               class="btn btn-sm btn-primary btn-round">Перейти</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        {% if is_paginated %}
            <nav class="my-4">
                <ul class="pagination justify-content-center">
                    {% if page_obj.has_previous %}
                        <li class="page-item disabled">
                            <a class="page-link" href="javascript:void(0)">«</a>
                        </li>
                    {% endif %}
                    {% for num_page in page_obj.paginator.num_pages %}
                        <li class="page-item {% if page_obj.number == num_page %}active{% endif %}">
                            <a class="page-link" href="javascript:void(0)">{{ num_page }}</a>
                        </li>
                    {% endfor %}
                    {% if page_obj.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="javascript:void(0)">»</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        {% endif %}
    </div>
{% endblock %}

{% block css %}
    <link rel="stylesheet" href='{% static "libs/dropzone/dropzone.css" %}'>
    <link rel="stylesheet" href='{% static "css/widgets/file-preview.css" %}'>
{% endblock %}

{% block extrascripts %}
    {% include 'partials/dropezone_script.html' %}
    <script src='{% static "js/file_previews.js" %}'></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#show-preview-button').hide().click(function () {
                $(prKeySh(activePreviewId)).hide()
                $('#show-preview-button').hide()
            });

            let current_page = 1
            let page_param = window.location.search.match(/(\?|&)page\=([^&]*)/);

            if (page_param) {
                current_page = decodeURIComponent(page_param[2]);
            }

            var path = "?page=" + current_page + "&doc_type={{doc_type}}"
            if ($('.text-dark').length > 0 && $('.text-dark').data('id')) {
                path += "&sub_type=" + $('.text-dark').data("id")
            }

            $('#documents_wraper').load("{% url 'load_docs' %}" + path);
            $('#pagination').load("{% url 'load_paginations_docs' %}" + path);
            bindPreviewEvents()
        });

        function load_tech_cards_docs(element) {
            comole.log('here')
            event.preventDefault();
            $('.nav-mm').removeClass('text-dark');
            element.addClass('text-dark');
            $('input[name="sub_type"').val(element.data("id"));
            $('#documents_wraper').load("{% url 'load_docs' %}?doc_type={{doc_type}}&sub_type=" + element.data("id"))
            $('#pagination').load("{% url 'load_paginations_docs' %}?doc_type={{doc_type}}&sub_type=" + element.data("id"));
            bindPreviewEvents()
            return false;
        }
    </script>
{% endblock %}

mickroservices/templates/news.html
{% extends 'layout.html' %}
{% load wagtailcore_tags %}

{% block body_class %}template-blogindexpage{% endblock %}

{% block title %}Новости{% endblock %}

{% block page_title %}
    <h2 class="text-light font-weight-normal mt-4 mb-1">Новости
        {% if user.user_profile.user_is_manager %}
    <a href="{% url 'mickroservices:news_new' %}" class="btn btn-round btn-outline-primary btn-sm">Добавить новость</a>

    {% endif %}
    </h2>
{% endblock %}

{% block  breadcrumb%}
        {% include 'partials/breadcrumb.html' %}
{% endblock %}

{% block content %} 
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    <div class="my-5">
        <div class="row">
            {% for new in news reversed %}
                {% include "partials/item_preview.html"  with post=new %}
            {% empty %}
                Новых постов нет
            {% endfor %}
        </div>
    </div>
    {% if is_paginated %}
        {% include 'partials/pagination.html' with posts=page_obj %}
    {% endif %}
{% endblock %}

mickroservices/templates/user_edit.html
 {% extends 'user_new.html' %}
{% load static %}


{% block title %}Редактировать франчайзи{% endblock %}
{% block page_title %}
    <h2 class="text-light font-weight-normal mt-4 mb-1">Редактировать франчайзи</h2>
{% endblock %}

{% block  breadcrumb%}
    {% include 'partials/breadcrumb.html' %}
{% endblock %}
          {% block img %}
                        <div class="form-group">
                            <label class="form-label w-100">Фото</label>
                           {{ form_wagtail.avatar }}
                        </div>
                {% endblock %}
{% block create %}
{% endblock %}