sushi_app/urls.py
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.urls import path

from . import views
from .forms import LoginForm
from .reset_views import PasswordResetView,PasswordResetCompleteView,PasswordResetDoneView,PasswordResetConfirmView

urlpatterns = [
    path('delete-directory', views.delete_directory),
    path('delete-directory-file', views.delete_directory_file),
    path('show-directories', views.show_directories),
    path('add-directory-file', views.add_directory_file),
    path('add-directory', views.add_directory),
    path(
        '', views.base, name='base'),
    path(
        'accounts/login/',
        auth_views.LoginView.as_view(
            template_name='authentication_login.html',
            authentication_form=LoginForm), name='login'),
    path(
        'accounts/reset/',
        PasswordResetView.as_view(), name='password_reset'),
    path('accounts/password_reset/done/',
         PasswordResetDoneView.as_view(),
         name='password_reset_done'),

    path('accounts/reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('accounts/reset/done/',
         PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
    path(
        'logout',
        auth_views.LogoutView.as_view(next_page="login"),
        name='logout'),
    path(
        'search', views.search, name='search'),
    path('employee/<int:user_id>', views.employee_info, name='employee_info'),
    path('employee/<int:user_id>/shops_by_sign/<int:sign_id>', login_required(views.EmployeeSignShopsView.as_view()),
         name='employee_sign_shops'),
    path('employee/all', views.employee_list, name='employee_list'),
    path('faq-all', views.faq_list, name='faq_list'),
    path('faq/<int:faq_id>', views.faq_answer, name='faq_answer'),
    path('manager-lk', views.manager_lk_view, name='manager_lk'),
    path('partner-lk', views.partner_lk_view, name='partner_lk'),
    path('partner/new', views.create_partner_view, name='create_partner'),
    path('partner/<int:user_id>', login_required(views.PartnerDetailView.as_view()), name='partner_info'),
    path('partner/edit/<int:user_id>', views.edit_partner_view, name='edit_partner'),
    path('partner/delete/<int:user_id>', login_required(views.PartnerDeleteView.as_view()), name='delete_partner'),
    path('employee/new', views.create_employee_view, name='create_employee'),
    path('employee/edit/<int:user_id>', views.edit_employee_view, name='edit_employee'),
    path('employee/<int:user_id>/tasks/', views.EmployeeTasksListView.as_view(), name='employee_tasks_list'),
    path(
        'request/new', views.form_request_view, name='form_request'),
    path(
        'review/<int:partner_id>/new', views.feedback_form_view, name='form_review'),
    path('notification', views.notification_view, name='notification'),
    path('shop/new', views.shop_form_view, name='shop_form'),
    path(
        'shop/<int:shop_id>',
        login_required(views.ShopListView.as_view()),
        name='shop'),
    path('shop/<int:shop_id>/edit', login_required(views.ShopFormView.as_view()), name='shop_edit'),
    path('shop/<int:shop_id>/delete', login_required(views.ShopDeleteView.as_view()), name='shop_delete'),
    path('shop_sign_detail/<int:pk>', login_required(views.ShopSignDetailView.as_view()), name='shop_sign_detail'),
    path('shop_sign_edit/<int:pk>', login_required(views.ShopSignEditView.as_view()), name='shop_sign_edit'),
    path(
        'task/new/<int:partner_id>', views.form_task_view, name='form_task'),
    path(
        'task/<int:task_id>-<int:user_id>', views.task_view, name='task'),
    path(
        'request/<int:requests_id>-<int:user_id>', views.requests_view, name='request'),
    path(
        'review/<int:feedback_id>-<int:user_id>', views.feedback_view, name='feedback'),
    path('load/request', views.load_filtered_request, name='load_filtered_request'),
    path('load/feedback-shop/<int:shop_id>', views.load_filtered_shop_feedback, name='load_filtered_shop_feedback'),
    path('load/feedback', views.load_filtered_feedback, name='load_filtered_feedback'),
    path('load/tasks', views.load_filtered_tasks, name='load_filtered_tasks'),
    path('load/idea', views.load_filtered_idea, name='load_filtered_ideas'),
    path('load_paginations_docs', views.load_paginations_docs, name='load_paginations_docs'),
    path('load_docs', views.load_docs, name='load_docs'),
    path('load_docs_info/', views.load_docs_info, name='load_docs_info'),
    path('load_notifications/', views.load_notifcations, name='load_notifcations'),
    path('load_pdf_stream_preview/<int:doc_id>', views.load_pdf_stream_preview, name='load_pdf_stream_preview'),
    path('load_excel/<int:doc_id>', views.load_excel, name='load_excel'),
    path('preview-deprecated/<doc_type>/<int:doc_id>', views.preview_deprecated, name='preview_deprecated'),
    path('preview/<doc_type>/<int:doc_id>', views.preview, name='preview'),
    path('notification-settings/', views.notification_settings_view, name='notification_settings'),
    path('notification-rules', views.update_notification_rules, name='notification_rules'),
    path('notification-events', views.notifcation_events, name='notification_events'),
]

sushi_app/models.py
import os

import wagtail.users.models
import wagtail.users.models
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models
from mptt.models import MPTTModel, TreeForeignKey
from phonenumber_field.modelfields import PhoneNumberField
from wagtail.core.fields import RichTextField
from wagtail.documents.models import Document, AbstractDocument

from mickroservices.models import DocumentSushi
from sushi_app.utils import create_dict_from_choices
from .enums import *
from .enums import *


class Directory(MPTTModel):
    title = models.CharField("Название", max_length=100)
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')

    class Meta:
        verbose_name = "Папка"
        verbose_name_plural = "Папки"

    def __str__(self):
        return self.title


def get_upload_path(instance, filename):
    return os.path.join('directory_files', instance.directory.title, filename)


class DirectoryFile(models.Model):
    directory = models.ForeignKey(Directory, related_name='directory_files', on_delete=models.CASCADE)
    dir_file = models.FileField("Файл", upload_to=get_upload_path)

    def filename(self):
        return os.path.basename(self.dir_file.name)


class Department(models.Model):
    name = models.CharField(max_length=256, db_index=True)

    def __str__(self):
        return f"{self.name}"


class UserProfile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='user_profile'
    )
    wagtail_profile = models.OneToOneField(
        wagtail.users.models.UserProfile, on_delete=models.CASCADE, related_name='user_profile',
        null=True, blank=True
    )
    position = models.CharField(max_length=100, blank=True)
    phone_number = PhoneNumberField(null=True, blank=True)
    whatsapp = PhoneNumberField(null=True, blank=True)
    twitter = models.URLField(null=True, max_length=200, blank=True)
    facebook = models.URLField(null=True, max_length=200, blank=True)
    instagram = models.URLField(null=True, max_length=200, blank=True)
    key_responsibilities = RichTextField(blank=True)
    is_partner = models.BooleanField(default=False)
    is_manager = models.BooleanField(default=False)
    is_head = models.BooleanField(blank=True, default=False)
    manager = models.ForeignKey(on_delete=models.SET_NULL, to='self', related_name='partner',
                                null=True, blank=True, limit_choices_to={'is_manager': True})
    head = models.ForeignKey(on_delete=models.SET_NULL, to='self', related_name='employee',
                             null=True, blank=True, limit_choices_to={'is_head': True})
    department = models.ForeignKey(on_delete=models.SET_NULL, to=Department, related_name='member',
                                   null=True, blank=True)
    scan = models.FileField(upload_to='images', blank=True)
    middle_name = models.CharField(max_length=100, null=True, blank=True)
    ddk_number = models.CharField(max_length=200, null=True, blank=True)
    comment = models.TextField(null=True, blank=True, verbose_name="Комментарий к пользователю")

    def __str__(self):
        return self.user.get_full_name()

    @property
    def user_is_manager(self):
        return self.is_manager or self.is_head

    def save(self, *args, **kwargs):
        models = []
        ll = {
            'request',
            'messege',
            'question',
            'news',
            'feedback',
            'shop',
            'idea',
            'materials',
        }
        for ls in ll:
            sub = Subscribes(user_id=self.user,
                             event_type=ls,
                             subscribe_type='site')
            models.append(sub)
            sub = Subscribes(user_id=self.user,
                             event_type=ls,
                             subscribe_type='email')
            models.append(sub)
        Subscribes.objects.bulk_create(models)
        super().save(*args, **kwargs)


class Task(models.Model):
    responsible = models.ForeignKey(on_delete=models.CASCADE, to=settings.AUTH_USER_MODEL,
                                    related_name='task_responsible')
    manager = models.ForeignKey(on_delete=models.CASCADE, to=UserProfile, related_name='task_manager',
                                limit_choices_to={'is_manager': True})
    title = models.CharField(max_length=256)
    description = models.TextField()
    date_create = models.DateTimeField(auto_now_add=True)
    status = models.SmallIntegerField(choices=STATUS_CHOICE, default=ST_IN_PROGRESS)

    def __str__(self):
        return '{0} | {1} | {2}'.format(
            self.id,
            self.date_create,
            create_dict_from_choices(STATUS_CHOICE)[self.status]
        )


class Requests(models.Model):
    responsible = models.ForeignKey(on_delete=models.CASCADE, to=settings.AUTH_USER_MODEL,
                                    related_name='requests_responsible')
    manager = models.ForeignKey(on_delete=models.CASCADE, to=UserProfile, related_name='requests_manager',
                                limit_choices_to={'is_manager': True})
    title = models.CharField(max_length=256)
    description = models.TextField()
    date_create = models.DateTimeField(auto_now_add=True)
    status = models.SmallIntegerField(choices=STATUS_CHOICE, default=ST_IN_START)

    def __str__(self):
        return '{0} | {1} | {2}'.format(
            self.id,
            self.date_create,
            create_dict_from_choices(STATUS_CHOICE)[self.status]
        )


class RequestFile(models.Model):
    request = models.ForeignKey(Requests, on_delete=models.CASCADE, related_name='files')
    file = models.FileField(upload_to='requests', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)


class ShopSign(models.Model):
    title = models.CharField(max_length=255, verbose_name='Наименование')
    icon = models.ImageField('Иконка', blank=True, null=True)

    def __str__(self):
        return f"{self.title}"

    class Meta:
        verbose_name = 'Признак магазин'
        verbose_name_plural = 'Признаки магазинов'


class Shop(models.Model):
    address = models.CharField(max_length=255, blank=False, null=False,
                               verbose_name='Адрес магазина')
    city = models.CharField(max_length=255)
    entity_name = models.CharField(max_length=255)
    docs = models.ManyToManyField(
        DocumentSushi,
        blank=True,
        related_name='+'
    )
    checks = models.ManyToManyField(
        DocumentSushi,
        blank=True,
        related_name='+'
    )
    partner = models.ForeignKey(on_delete=models.DO_NOTHING, to=UserProfile,
                                limit_choices_to={'is_partner': True}, related_name='shop_partner')
    responsibles = models.ManyToManyField(to=UserProfile,
                                          limit_choices_to={'is_manager': True}, related_name='shop_responsible')
    date_create = models.DateTimeField(auto_now_add=True)
    file = models.FileField(blank=True)
    details = models.TextField(blank=True)
    signs = models.ManyToManyField(ShopSign, blank=True,
                                   related_name='shop_sings')

    def __str__(self):
        return f"{self.city} {self.address}"

    class Meta:
        verbose_name = 'Магазин'
        verbose_name_plural = 'Магазины'


class Product(models.Model):
    user = models.ForeignKey(on_delete=models.CASCADE, to=settings.AUTH_USER_MODEL, related_name='user')
    title = models.CharField(max_length=256)
    short_descrip = models.CharField(max_length=256)
    descrip = models.TextField()
    composition = models.TextField()
    characteristics = models.TextField()
    date_update = models.DateTimeField(auto_now=True, blank=True, null=True)
    date_create = models.DateTimeField(auto_now_add=True)
    RATING_CHOICE = (
        (1, "Ужасно"),
        (2, "Плохо"),
        (3, "Нормально"),
        (4, "Хорошо"),
        (5, "Отлично"),
    )
    rating = models.IntegerField(choices=RATING_CHOICE, default=5)
    files = models.ImageField(blank=True)

    def __str__(self):
        return f" {self.title}, дата: {self.date_create}"

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'


class Feedback(models.Model):
    ST_SOLVED, ST_NOT_SOLVED = range(2)
    STATUS_CHOICE = (
        (ST_SOLVED, "Отработан"),
        (ST_NOT_SOLVED, "Не отработан"),
    )
    responsible = models.ForeignKey(on_delete=models.CASCADE, to=UserProfile,
                                    related_name='feed_responsible')
    manager = models.ForeignKey(on_delete=models.CASCADE, to=UserProfile, related_name='feed_manager',
                                limit_choices_to={'is_manager': True})
    shop = models.ForeignKey(on_delete=models.CASCADE, to=Shop)
    date_create = models.DateTimeField(auto_now_add=True)
    date_pub = models.DateField()
    status = models.SmallIntegerField(choices=STATUS_CHOICE, default=ST_NOT_SOLVED)
    description = models.TextField()
    source = models.CharField(max_length=256)

    def __str__(self):
        return '{0} | {1} | {2}'.format(
            self.id,
            self.date_create,
            create_dict_from_choices(STATUS_CHOICE)[self.status]
        )


class Messeges(models.Model):
    from_user = models.ForeignKey(on_delete=models.CASCADE, to=settings.AUTH_USER_MODEL, related_name='user_messeges')
    to_user = models.ForeignKey(on_delete=models.CASCADE, to=settings.AUTH_USER_MODEL, related_name='to_user')
    task = models.ForeignKey(on_delete=models.CASCADE, to=Task, blank=True, null=True)
    requests = models.ForeignKey(on_delete=models.CASCADE, to=Requests, blank=True, null=True)
    feedback = models.ForeignKey(on_delete=models.CASCADE, to=Feedback, blank=True, null=True)
    text = models.TextField(null=True, blank=True)

sushi_app/templates/add-directory.html
<div class="add-directory-panel">
  <div class="modal-close">X</div>
  <div class="add-directory-name">
    Название директории <input type="text" placeholder="Имя папки" id="directory-name">
  </div>
  <div class="add-directory-submit">
    <input type="button" value="Добавить" class="complete-add-dir">
  </div>
</div>

sushi_app/templates/dashboard_partner.html
{% extends 'layout.html' %}
{% load static %}

{% block css %}<link rel="stylesheet" href="{% static "libs/dropzone/dropzone.css" %}">{% endblock %}

{% block title %}Личный кабинет{% endblock %}
{% block page_title %}
    <h2 class="text-light font-weight-normal mt-4 mb-1">Личный кабинет
    <a href="{% url 'form_request' %}" class="btn btn-round btn-outline-primary btn-sm">Поставить задачу менеджеру</a>
    </h2>

{% endblock %}

{% block  breadcrumb%}
    {% include 'partials/breadcrumb.html' %}
{% endblock %}
    {% block content %}

                    <div class="row">
                        <div class="col">

                            <div class="media align-items-center mb-3">
                                {% if manager.wagtail_profile.avatar %}
                                    <a href="{% url 'employee_info' manager.user.id %}" >  <img src="{{ manager.wagtail_profile.avatar.url }}" alt="" class="ui-w-60 rounded-circle"></a>
                                {% endif %}
                                <div class="small ml-3">
                                    <div class="text-muted">Ваш менеджер</div>
                                    <a href="{% url 'employee_info' manager.user.id %}" class="text-primary">{{ manager.user.get_full_name }}</a>
{#                                    <a href="#" class="btn btn-xs btn-round btn-outline-dark">Написать в чат</a>#}
                                </div>
                            </div>
                        </div>
                    </div>
{#                    <div class="py-1 mb-2">#}
{#                        <div class="input-group">#}
{#                            <input type="text" class="form-control" placeholder="Введите запрос">#}
{#                            <div class="input-group-append">#}
{#                                <button type="button" class="btn btn-primary">#}
{#                                    <i class="ion ion-ios-search"></i>&nbsp; Поиск</button>#}
{#                            </div>#}
{#                        </div>#}
{#                    </div>#}
                    <div class="row">
                        <div class="col">
                            <div class="nav-tabs-top mb-4">
                                <ul class="nav nav-tabs">
                                    <li class="nav-item">
                                        <a class="nav-link active show" data-toggle="tab" href="#shops">Магазины</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" data-toggle="tab" href="#requests">Поручил задачи<span class="badge badge-pill badge-primary indicator">{{ requests_not_solved }}</span></a>
                                    </li>

                                    <li class="nav-item">
                                        <a class="nav-link" data-toggle="tab" href="#tasks">Делаю задачи<span class="badge badge-pill badge-primary indicator">{{ task_not_solved }}</span></a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" data-toggle="tab" href="#reviews">Отзывы<span class="badge badge-pill badge-primary indicator">{{ feedback_not_solved }}</span></a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link" data-toggle="tab" href="#files">Файлы</a>
                                    </li>
                                                                        <li class="nav-item">
                                      <a class="nav-link" href="{% url "mailing:mailing_view_list" %}">Новости</a>
                                    </li>
                                </ul>
                                <div class="tab-content no-shadow">
                                    <div class="tab-pane fade active show" id="shops">
                                        <div class="my-4 row">
                                            {% for shop in shop_list %}
                                            <div class="col-md-6 mb-4">
                                                <div class="card hoverable h-100">
                                                    <div class="card-header d-flex justify-content-between  align-items-start">
                                                        <div>
                                                            <div class="h5 mb-0 font-weight-semibold">{{ shop.address }}</div>
                                                        </div>

                                                        <div class="btn-group project-actions">
                                                            <button type="button"
                                                                    class="btn btn-sm btn-default icon-btn borderless btn-round md-btn-flat dropdown-toggle hide-arrow"
                                                                    data-toggle="dropdown">
                                                                <i class="ion ion-ios-more"></i>
                                                            </button>
                                                            <div class="dropdown-menu dropdown-menu-right">
                                                                <a class="dropdown-item"
                                                                   href="{% url 'shop' shop.id %}">Просмотр</a>
                                                                <a class="dropdown-item"
                                                                   href="{% url 'shop_delete' shop.id %}">Удалить</a>
                                                                {#                                                                <a class="dropdown-item" href="javascript:void(0)">Edit</a>#}
                                                                {#                                                                <a class="dropdown-item" href="javascript:void(0)">Remove</a>#}
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="card-body">
                                                        <div class="font-weight-semibold">Файлы</div>
                                                        {% for doc in shop.docs.all %}
                                                            <div class="mb-1 d-inline-block mr-3">
                                                                <span class="small text-muted">{{ doc.title }}</span>
                                                            <a href="{{ doc.url }}" class="text-primary"><span class="ion-ios-search"></span></a>
                                                            <a href="{{ doc.url }}" class="text-primary"><span class="ion-md-cloud-download"></span></a>
                                                        </div>
                                                       {% endfor %}
                                                        <div class="font-weight-semibold">Последние проверки</div>
                                                        {% for check in shop.checks.all %}
                                                        <div class="mb-1 d-inline-block mr-3">
                                                            <span class="small text-muted">{{ check.title }}</span>
                                                            <a href="{{ check.url }}" class="text-primary"><span class="ion-ios-search"></span></a>
                                                            <a href="{{ check.url }}" class="text-primary" download=""><span class="ion-md-cloud-download"></span></a>
                                                        </div>
                                                       {% endfor %}

                                                    </div>
                                                </div>
                                            </div>
                                            {% endfor %}

                                        </div>
                                    </div>
                                    <div class="tab-pane fade" id="requests">
                                        <div class="my-4 small text-right">
                                            <span class="text-muted">Фильтровать:</span>
                                            <a href="{%url 'load_filtered_request' %}" class="text-muted active" onclick="load_request($(this))">Все</a>
                                            <a href="{%url 'load_filtered_request' %}?filter_request=0" class="text-muted" onclick="load_request($(this))">Решен</a>
                                            <a href="{%url 'load_filtered_request' %}?filter_request=1" class="text-muted" onclick="load_request($(this))">Обрабатывается</a>
                                            <a href="{%url 'load_filtered_request' %}?filter_request=2" class="text-muted" onclick="load_request($(this))">Отклонен</a>
                                        </div>
                                          <div id="request_manager" class="my-4 row">
                                            {% include 'partials/request_manager.html'%}
                                        </div>
                                    </div>
                                    <div class="tab-pane fade" id="tasks">
                                        <div class="my-4 small text-right">
                                            <span class="text-muted">Фильтровать:</span>
                                            <a href="{%url 'load_filtered_tasks' %}" class="text-muted active" onclick="load_tasks($(this))">Все</a>
                                            <a href="{%url 'load_filtered_tasks' %}?filter_task=0" class="text-muted" onclick="load_tasks($(this))">Решен</a>
                                            <a href="{%url 'load_filtered_tasks' %}?filter_task=1" class="text-muted" onclick="load_tasks($(this))">Обрабатывается</a>
                                            <a href="{%url 'load_filtered_tasks' %}?filter_task=2" class="text-muted" onclick="load_tasks($(this))">Отклонен</a>
                                        </div>
                                        <div id="tasks_manager" class="my-4 row">
                                            {% include 'partials/tasks_manager.html'%}
                                        </div>
                                    </div>
                                    <div class="tab-pane fade" id="reviews">
                                        <div class="my-4 small text-right">
                                            <span class="text-muted">Фильтровать:</span>
                                            <a href="{%url 'load_filtered_feedback' %}" class="text-muted active" onclick="load_feedback($(this))">Все</a>
                                            <a href="{%url 'load_filtered_feedback' %}?filter_feedback=0" class="text-muted" onclick="load_feedback($(this))">Отработан</a>
                                            <a href="{%url 'load_filtered_feedback' %}?filter_feedback=1" class="text-muted" onclick="load_feedback($(this))">Не отработан</a>
                                        </div>
                                       <div id="feedback_manager" class="my-4 row">
                                            {% include 'partials/feedback_manager.html'%}
                                        </div>
                                    </div>
                                    <div class="tab-pane fade" id="files">

                                        <div class="my-4 small text-right">
                                            <span class="text-muted">Сортировать: </span>
                                            <a href="#" class="text-muted active">По порядку</a>
                                            <a href="#" class="text-muted">По дате</a>
                                            <a href="#" class="text-muted">По размеру</a>
                                        </div>
                                        <div class="row"  id="documents_wraper">
                                            {% include 'partials/documents.html' with documents=documents %}
                                        </div>
                                        <div id="pagination">
                                        {% if is_paginated %}
                                            {% include 'partials/pagination.html' with posts=page_obj %}
                                        {% endif %}
                                        </div>  
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
{% endblock %}
{% block extrascripts %}
    <script src="{% static "libs/dropzone/dropzone.js" %}"></script>
    <script src="{% static "js/dashboard.js" %}"></script>
{% endblock %}

sushi_app/templates/file_preview.html
<div class="preview-content">
    {% if doc_type == 'embed' %}
        <embed class="preview-internal" id="{{ doc_id }}" src="{{ doc_url }}" type="application/pdf">
    {% elif doc_type == 'image'%}
        <img class="preview-img" id="{{ doc_id }}" src="{{ doc_url }}">
    {% elif doc_type == 'excel'%}
        <div class="table-wrapper table-responsive" id="{{ doc_id }}" ></div>
    {% elif doc_type == 'clear_pdf'%}
        <embed class="preview-internal"  id="{{ doc_id }}" src="/load_pdf_stream_preview/{{ doc_id }}" type="application/pdf">
    {% endif %}
</div>

sushi_app/templates/file_preview_deprecated.html
{% extends 'layout.html' %}
{% load static %}
{% load wagtailcore_tags %}

{% block body_class %}template-blogindexpage{% endblock %}


{% block title %}Предпросмотр{% endblock %}

{% block page_title %}
    <h2 class="text-light font-weight-normal mt-4 mb-1">Предпросмотр</h2>
{% endblock %}

{% block  breadcrumb%}
        {% include 'partials/breadcrumb.html' %}
{% endblock %}

{% block content %} 
<div class="preview-content">
    {% if doc_type == 'embed' %}
        <embed class="preview-internal" id="{{ doc_id }}" src="{{ doc_url }}" type="application/pdf">
    {% elif doc_type == 'image'%}
        <img class="preview-img" id="{{ doc_id }}" src="{{ doc_url }}">
    {% elif doc_type == 'excel'%}
        <div class="table-wrapper table-responsive" id="{{ doc_id }}" ></div>
    {% elif doc_type == 'clear_pdf'%}
        <embed class="preview-internal"  id="{{ doc_id }}" src="/load_pdf_stream_preview/{{ doc_id }}" type="application/pdf">
    {% endif %}
</div>
{% endblock %}

{% block css %}
    <link rel="stylesheet" href='{% static "css/widgets/file-preview.css" %}'>
{% endblock %}

{% block extrascripts %}
    <script src='{% static "js/file_previews.js" %}'></script>
    <script type="text/javascript">
        let docType = '{{ doc_type }}'
        let docId = '{{ doc_id }}'

        if (docType === 'excel'){
            $(`#${docId}`).load('/load_excel/'+ docId, function(){
                    $('table').attr('class', 'table')
                    $('table thead th').attr('scope', 'col')
                    $('table tbody tr th').attr('scope', 'row')
                })
        }
    </script>
{% endblock %}