mickroservices/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from mickroservices import views

app_name = 'mickroservices'

urlpatterns = [
    path('faq/',
         login_required(views.QuestionView.as_view()),
         name='faq'),

    path('ideas/',
         login_required(views.IdeaView.as_view()),
         name='idea'),

    path('lessons/',
         login_required(views.CoursesView.as_view()),
         name='lessons'),
    path('lesson/<int:pk>',
         login_required(views.CourseView.as_view()),
         name='lesson'),

    path('news/',
         login_required(views.NewsView.as_view()),
         name='news'),
    path('news/new/',
         login_required(views.NewsCreateView.as_view()),
         name='news_new'),
    path('news/edit/<int:pk>',
         login_required(views.NewsEditView.as_view()),
         name='news_edit'),
    path(
        'news/delete/<int:pk>',
        login_required(views.NewsDeleteView.as_view()),
        name='news_delete'
    ),
    path('marketing/',
         login_required(views.MarketingView.as_view()),
         name='marketing'),

    path('schedule/<int:pk>',
         login_required(views.ScheduleView.as_view()),
         name='schedule_view'),
    path('schedule/new/',
         login_required(views.ScheduleCreateView.as_view()),
         name='schedule_new'),
    path('schedule/',
         login_required(views.ScheduleListView.as_view()),
         name='schedule'),
    path('tech_cards/',
         login_required(views.TechCardsListView.as_view()),
         name='tech_cards'),
    path('regulations/',
         login_required(views.RegulationsListView.as_view()),
         name='regulations'),    
]

mickroservices/templates/mickroservices/news_page.html
{% extends 'layout.html' %}

{% load wagtailcore_tags %}
{% load wagtailcore_tags wagtailimages_tags %}
{% load widget_tweaks %}
{% load static %}

{% block title %}{{ page.title }}{% endblock %}

{% block body_class %} template-homepage{% endblock %}

{% block page_title %}<h2 class="text-light font-weight-normal mt-4 mb-1">{{ page.title }}
    {% if user.user_profile.user_is_manager %}
        <a href="{% url 'mickroservices:news_edit' page.id %}" class="btn btn-round btn-outline-primary btn-sm">Редактировать
            новость</a>
        <a href="{% url 'mickroservices:news_delete' page.id %}" target="_blank"
           class="btn btn-round btn-outline-primary btn-sm">Удалить новость</a>
    {% endif %}
</h2>{% endblock %}

{% block  breadcrumb %}
    {% include 'partials/breadcrumb.html' %}
{% endblock %}

{% block content %}
    <div class="mb-4 text-muted small text-uppercase">
        {{ page.owner }} - {{ page.first_published_at }}
    </div>
    {% image page.image max-896x597 %}
    <div class="ql-content">
        <p>{{ page.body | richtext }}</p>
    </div>
{% endblock %}

{% block extracss %}
    <link rel="stylesheet" href='{% static "libs/quill/typography.css" %}'>
{% endblock %}